org.gradle.jvmargs=-Xmx1G
org.gradle.daemon=true
org.gradle.parallel=true
org.gradle.caching=true
org.gradle.configuration-cache=true

parchment_minecraft_version=1.21.1
parchment_mappings_version=2024.11.17
minecraft_version=1.21.1
minecraft_version_range=[1.21,1.22)

neo_version=21.1.152
loader_version_range=[1,)

mod_id=create_cog_hud
mod_name=Create: Cog HUD
mod_license=MIT
mod_version=1.0.0
mod_group_id=euphy.upo.create_cog_hud
mod_authors=upo
mod_description=HUD in Create style.

systemProp.http.proxyHost=127.0.0.1
systemProp.http.proxyPort=7890
systemProp.https.proxyHost=127.0.0.1
systemProp.https.proxyPort=7890